---
- hosts: vaje-vsi
  remote_user: administrator
  tasks:

    - name: import VM
      command: VBoxManage import ElementaryOS.ova
      args:
        chdir: /home/student/VirtualDrives/
      become: true
      become_user: student

    - name: make VM disk immutable
      command: chattr +i ElementaryOS*
      args:
        chdir: /home/student/VirtualBox VMs/Standard/
      become: true
      become_method: sudo

    - name: set disk immutable
      command: VBoxManage modifyhd XXX --type immutable
      args:
        chdir: /home/student/VirtualBox VMs/Standard/
      become: true
      become_user: student

