---
- hosts: vaje-vsi
  remote_user: administrator
  become: true
  become_method: sudo
  tasks:

    - name: add user
      user:
        name=student
        password=...

    - name: add pycharm repo
      apt_repository:
        repo='ppa:mystic-mirage/pycharm'

    - name: check for aptitude
      apt: name=aptitude state=latest

    - name: update system
      apt:
        update_cache=yes
        upgrade=full

    - name: install git pycharm and virtualbox
      apt:
        name=git-all state=present
        name=pycharm-community state=present
        name=virtualbox state=present
